In [1]:
!pip install python-dotenv sqlalchemy psycopg2-binary

Requirement already satisfied: python-dotenv in C:\Users\Mujakkir\AppData\Local\Programs\Python\Python312\Lib\site-packages (1.2.4)
Requirement already satisfied: sqlalchemy in C:\Users\Mujakkir\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.0.45)
Requirement already satisfied: psycopg2-binary in C:\Users\Mujakkir\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in C:\Users\Mujakkir\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Mujakkir\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sqlalchemy) (4.15.0)

In [ ]:
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine



load_dotenv()
engine = create_engine(f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}")

# Load the table
df = pd.read_sql_table("pos_sales_data", engine, schema="public")
df.head()

,billingdate,region,product,quantity,unitprice,storelocation,customertype,discount,salesperson,totalprice,paymentmethod,promotion,returned,orderid,customername,shippingcost,orderdate,deliverydate,regionmanager
0,2023-02-23,East,Laptop,14,163.60,Store B,Wholesale,0.00,Eva,2290.40,Online,FREESHIP,0,REG100000,Cust 6583,43.34,2023-02-23,2023-02-27,Eric
1,2024-12-19,South,Phone,1,544.01,Store A,Retail,0.00,Alice,544.01,Gift Card,SAVE10,0,REG100001,Cust 2144,5.30,2024-12-19,2024-12-28,Sophie
2,2023-05-10,North,Desk,14,346.18,Store B,Wholesale,0.10,Alice,4361.87,Online,WINTER15,0,REG100002,Cust 5998,20.46,2023-05-10,2023-05-19,Ryan
3,2025-02-26,Central,Chair,18,384.82,Store A,Wholesale,0.15,Frank,5887.75,Gift Card,FREESHIP,0,REG100003,Cust 7136,27.95,2025-02-26,2025-03-02,Cameron
4,2023-06-24,East,Desk,18,237.76,Store C,Retail,0.00,Carlos,4279.68,Online,SAVE10,0,REG100004,Cust 6506,5.73,2023-06-24,2023-06-27,Eric

In [3]:
from sqlalchemy import inspect

inspector = inspect(engine)
tables = inspector.get_table_names()
for table in tables:
    print(f"Table: {table}")

Table: pos_sales_data
Table: sales
Table: students
Table: marks
Table: sub_marks
Table: product_tbl
Table: order_tbl

In [ ]:
import sys
print(sys.executable)

In [ ]:
# Dataset load to PostgreSQL

''' 
import os
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

# 1. Connect to PostgreSQL
engine = create_engine(f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}")

# 2. Read your Excel file
# UPDATE THIS PATH to where your Excel file is located
excel_file_path = r"D:\PDG in Data Analytics\3. Programing\Projects\nu-sales-analytics-project\data\sales_dataset.xlsx"
df = pd.read_excel(excel_file_path)

# 3. Insert into PostgreSQL
# 'sales' is the name of the table you want to create/populate
df.to_sql('sales', engine, if_exists='replace', index=False)

print("Data successfully loaded to PostgreSQL!")
'''

In [4]:
df = pd.read_sql_table("sales", engine, schema="public")

In [5]:
df

,Date,Transaction ID,Invoice No,Invoice type,Customer Name,Customer ID,Customer Type,Barcode,Product Name,Product Category,...,Invoice Value,Discount,Sales Amount,Sales VAT,Sales Return,Credited Amount,Payment Method,Bank Name,Remarks,Month Name
0,2025-03-09,TXN100001,INV10001,Cash Sale,M/S Nazma Store Store,CUST0106,Online,8834993708224,Wall Clock 2,Gift Items,...,7372.68,1105.90,6266.78,0.00,0.0,6266.78,Bkash,None,Advance Payment,March
1,2025-05-20,TXN100002,INV10002,Credit Sale,M/S Mohammadia Trading Store,CUST0155,Wholesale,8817094232227,Photo Frame 3,Gift Items,...,51918.40,0.00,51918.40,0.00,0.0,0.00,Cash,None,Regular Sale,May
2,2025-09-11,TXN100003,INV10003,Credit Sale,M/S Sajid & Brothers Store,CUST0195,Wholesale,8864775758589,Gift Box 2,Gift Items,...,220.45,11.02,209.43,0.00,0.0,0.00,Cash,None,Special Discount,September
3,2025-06-14,TXN100004,INV10004,Cash Sale,M/S Kagotia Crockeries Store,CUST0119,Online,8830160360945,Fan 2,Electronics,...,6123.60,122.47,6001.13,300.06,0.0,0.00,Cash,None,Wholesale Order,June
4,2025-01-16,TXN100005,INV10005,Corporate Order,M/S Daniel Wagner Construction,CUST0058,Corporate,8879637317274,Electric Kettle 4,Electronics,...,4723.06,0.00,4723.06,236.15,0.0,1487.76,Cash,None,Repeat Customer,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18997,2025-11-08,TXN118998,INV28998,Credit Sale,M/S Lisa Hensley Construction,CUST0192,Retailer,8820909870727,Fan 1,Electronics,...,2097.90,314.69,1783.21,89.16,0.0,0.00,Cash,None,Partial Payment,November
18998,2025-08-10,TXN118999,INV28999,Cash Sale,M/S Feroza Store Store,CUST0001,Retailer,8829473961937,Ladder 1,Hardware,...,17311.00,346.22,16964.78,0.00,0.0,5089.43,Cash,None,Wholesale Order,August
18999,2025-03-13,TXN119000,INV29000,Corporate Order,M/S Shinepukur Crockeries Store,CUST0200,Retailer,8838840768544,Wall Clock 4,Gift Items,...,5679.36,0.00,5679.36,0.00,0.0,1703.81,Bank,Islami Bank,Urgent Delivery,March
19000,2025-08-01,TXN119001,INV29001,Corporate Order,M/S Akondo Enterprise Store,CUST0167,Retailer,8841042286266,Bowl Set 2,Tableware,...,57780.00,0.00,57780.00,2889.00,0.0,0.00,Cash,None,Repeat Customer,August
19001,2025-03-09,TXN119002,INV29002,Credit Sale,M/S Silvia Crockerise Store,CUST0202,Retailer,8825734134727,Sauce Pan 3,Cookware,...,2633.50,263.35,2370.15,118.51,0.0,0.00,Cash,None,Special Discount,March

In [6]:
df.columns

Index(['Date', 'Transaction ID', 'Invoice No', 'Invoice type', 'Customer Name',
       'Customer ID', 'Customer Type', 'Barcode', 'Product Name',
       'Product Category', 'Sales by', 'Sales ID', 'Sales Zone', 'Zone Code',
       'Sales Channel', 'Purchase Value', 'Invoice Value', 'Discount',
       'Sales Amount', 'Sales VAT', 'Sales Return', 'Credited Amount',
       'Payment Method', 'Bank Name', 'Remarks', 'Month Name'],
      dtype='object')

In [7]:
df = pd.read_sql_table("students", engine, schema="public")
df.head()

   id  registration                name        phone  age      department
0   1   25868400016   Md. Sazidul Karim  01516379883   28  Data Analytics
1   2   25868400017    Md. Mehedi Hasan  01630408856   30  Data Analytics
2   3   25868400018       Md. Waliullah  01715803492   35  Data Analytics
3   4   25868400019  Md. Kawsar Hossain  01670928812   32  Data Analytics
4   5   25868400020      Mujakkir Ahmad  01787933422   27  Data Analytics